#!/usr/bin/env python3
"""PC-port inventory for this game: psxstack's tools/port_inventory.py (the probe, the link check, the counts)
configured for this tree (docs/PORT.md "The host-compile probe"). Adapted from dw2003recomp's
tools/port_inventory.py (docs/THIRD_PARTY.md).

  .venv/bin/python port/tools/port_inventory.py counts                 # the inventory's numbers on this tree
  .venv/bin/python port/tools/port_inventory.py counts --sites KIND    # file:line of every site of one kind
  .venv/bin/python port/tools/port_inventory.py probe [FILES...]       # host-compile gate at -m64 (exit 0 = clean)
  .venv/bin/python port/tools/port_inventory.py probe -v               # with the compiler's messages
  .venv/bin/python port/tools/port_inventory.py probe --warnings       # also count the non-gating -Wall warnings
  .venv/bin/python port/tools/port_inventory.py probe --m32            # the same at -m32 (compile only)
  .venv/bin/python port/tools/port_inventory.py link                   # probe, then nm: duplicate / undefined globals

The units are the ones `mk/version/us.mk` builds (MAIN_C_SRC and <OVERLAY>_C_SRC: the tree also holds jp/eu-only
files and the Psy-Q objects' C, which the shim replaces). The probe's objects go to build/port_inventory/m64/, its
override headers to build/port_inventory/include/; psxstack/tools/port_inventory.py's docstring describes the
commands and the site kinds. Two derived files are written there before every command:

  include/gte.h        every gte_* macro of include/gte.h as a no-op. The stack writes its override as
                       psyq/gtemac.h (the first game's name), which never shadows `#include "gte.h"`; this one is
                       first on the include path and carries the real header's guard. Goes away when psxstack names
                       the override after the game's header (or when port/include/gte.h, the host GTE, exists).
  psyq_symbols.txt     the Psy-Q names of config/us/symbols.txt's "PsyQ 4.7 SDK" section, grouped under the
                       `// LIBxxx.LIB/OBJ.OBJ` comments the stack reads to tell Psy-Q calls from game calls
                       (config/us/symbols.txt has one section for the whole SDK). The library and object come from
                       the src/main/psyq/<library>_<object>.c (or .s) that defines each name.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
PSXSTACK = ROOT / "psxstack"   # the stack: the submodule (scripts/worktree_init.sh checks it out)
VERSION = "us"
OUT = ROOT / "build" / "port_inventory"
sys.path.insert(0, str(PSXSTACK / "tools"))
import port_inventory as inv  # noqa: E402


# ---------------------------------------------------------------------------------------------------------------------
# The units: what mk/version/<version>.mk builds

def version_units(version=VERSION):
    """-> [Path] of every C unit <BINARY>_C_SRC lists, in the .mk's order."""
    text = (ROOT / "mk" / "version" / f"{version}.mk").read_text().replace("\\\n", " ")
    units = []
    for m in re.finditer(r"^(\w+)_C_SRC\s*:=\s*(.*)$", text, flags=re.M):
        body = m.group(2)
        for a in re.finditer(r"\$\(addprefix\s+(\S+),\s*([^)]*)\)", body):
            units += [a.group(1) + f for f in a.group(2).split()]
        units += re.sub(r"\$\(addprefix[^)]*\)", "", body).split()
    return [ROOT / u for u in units]


def module_of(rel):
    """src/main/system/task.c -> main/system; src/main/main.c -> main; src/kawseg/ui/kaw_hud.c -> kawseg/ui."""
    parts = rel.split("/")
    if parts[0] == "include":
        return "include/" + parts[-1]
    return "/".join(parts[1:-1]) if len(parts) > 3 else parts[1]


# ---------------------------------------------------------------------------------------------------------------------
# The derived files

def write_gte_override():
    """build/port_inventory/include/gte.h: every gte_* function-like macro of include/gte.h as ((void)0), under the
    real header's guard, so that the real one (MIPS inline asm) is skipped on the host."""
    real = ROOT / "include" / "gte.h"
    text = inv.strip_code(real.read_text(errors="replace"))
    guard = inv.include_guard(real) or "GTE_H"
    body = "".join(f"#define {n}{a} ((void)0)\n"
                   for n, a in re.findall(r"^[ \t]*#[ \t]*define[ \t]+(gte_\w+)(\([^)]*\))", text, flags=re.M))
    path = OUT / "include" / "gte.h"
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (f"/* generated by port/tools/port_inventory.py from include/gte.h; do not edit */\n"
               f"#ifndef {guard}\n#define {guard}\n{body}#endif\n")
    if not path.exists() or path.read_text() != content:
        path.write_text(content)


def psyq_definitions():
    """-> {name: (library, object)} for every function or datum a src/main/psyq/<library>_<object>.{c,s} defines."""
    where = {}
    for p in sorted((ROOT / "src" / "main" / "psyq").iterdir()):
        if p.suffix not in (".c", ".s"):
            continue
        lib, _, obj = p.stem.partition("_")
        lib, obj = lib.upper(), obj.upper()
        if p.suffix == ".s":
            names = re.findall(r"^\s*glabel\s+(\w+)", p.read_text(errors="replace"), flags=re.M)
        else:
            text = inv.strip_code(p.read_text(errors="replace"))
            names = re.findall(r"INCLUDE_ASM\([^,]+,\s*(\w+)\s*\)", text)
            # a definition: `type name(args) {` at the start of a line, not a prototype
            names += re.findall(r"^[A-Za-z_][\w\s\*]*?\b(\w+)\s*\([^;{}]*\)\s*\{", text, flags=re.M)
            # file-scope data: `type name[...] = ...;` or `type name;` without extern
            for m in re.finditer(r"^(?!\s*(?:extern|typedef|return)\b)[A-Za-z_][\w\s\*]*?\b(\w+)\s*(?:\[[^\]]*\]\s*)*(?:=|;)",
                                 text, flags=re.M):
                names.append(m.group(1))
        for n in names:
            where.setdefault(n, (lib, obj))
    return where


def write_psyq_symbols():
    """build/port_inventory/psyq_symbols.txt: the SDK section of config/us/symbols.txt under per-object
    `// LIBxxx.LIB/OBJ.OBJ` headers. -> (tagged, untagged names)."""
    lines = (ROOT / "config" / VERSION / "symbols.txt").read_text(errors="replace").splitlines()
    start = next(i for i, ln in enumerate(lines) if ln.startswith("// PsyQ"))
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("// ") and lines[i].strip() != "//"
                and not re.match(r"//\s*\w+\s*=\s*0x", lines[i])), len(lines))
    where = psyq_definitions()
    groups, untagged = {}, []
    for ln in lines[start + 1:end]:
        m = re.match(r"(\w+)\s*=\s*0x[0-9A-Fa-f]+\s*;", ln)
        if not m:
            continue
        name = m.group(1)
        if name in where:
            groups.setdefault(where[name], []).append(ln)
        else:
            untagged.append(ln)
    out = ["// Generated by port/tools/port_inventory.py from config/us/symbols.txt's PsyQ section; do not edit.",
           "// Each object's symbols under the comment psxstack's inventory reads as the library.", ""]
    for (lib, obj), ls in sorted(groups.items()):
        out += [f"// {lib}.LIB/{obj}.OBJ"] + ls + [""]
    if untagged:
        out += ["// Not placed in any src/main/psyq object (no library)"] + untagged + [""]
    path = OUT / "psyq_symbols.txt"
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(out)
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
    return sum(len(v) for v in groups.values()), [re.match(r"\w+", ln).group() for ln in untagged]


# ---------------------------------------------------------------------------------------------------------------------

CFG = inv.configure(
    root=ROOT, game_json=ROOT / "port/game/game.json",
    sources=version_units,
    headers=lambda: sorted((ROOT / "include").rglob("*.h")),
    include_dirs=[ROOT / "port/include", ROOT / "include", ROOT],
    symbol_files=[ROOT / "config" / VERSION / "symbols.txt"]
                 + sorted((ROOT / "config" / VERSION).glob("symbols_*.txt")) + [OUT / "psyq_symbols.txt"],
    module_of=module_of, gtemac=ROOT / "include/gte.h", include_asm=ROOT / "include/include_asm.h",
    port_h=ROOT / "include/port.h", psyq_dir=ROOT / "include", tool_dirs=[],
    defines=["VERSION_US", "SKIP_ASM"], out=OUT)


def main():
    ap, _ = inv.build_parser()
    write_gte_override()
    write_psyq_symbols()
    return inv.main(ap)


if __name__ == "__main__":
    sys.exit(main())
